debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.yoon.projectboard: debug
    org.springframework.web.servlet: debug    #request, response 만 log로 찍기 위해서
    org.hibernate.type.descriptor.sql.BasicBinder: trace    #query 를 바인딩 파라미터를 보기 위해서

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: board
    password: board
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true   #초기 데이터 생성 sql 실행 (data.sql)
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100       #벌크 사이즈 100개 한번에 select, 조회 성능 개선 -> n+1 쿼리 문제 해결
    open-in-view: false
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true

---

#spring:
#  config:
#    activate:
#      on-profile: testdb                 #@ActiveProfiles로 설정 시 설정파일
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql    #H2의 호환성 모드 : mysql과 가까운 환경에서 테스트 할 때
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
#  test.database.replace: none          #@DataJapTest를 동작할 떄 자동으로 test DB를 설정하는데 그 때 원하는 DB를 지정하려면
                                        #@AutoConfigureTestDatabases(replace = AutoConfigureTestDatabase.Replace.NONE) 지정을 해야한다.
                                        #하지만 테스트 클래스마다 설정하기 번거로울 때는 설정파일에 test.database.replace: none을 설정해주면 된다.
